[package]
name = "rustypdf-cli"
description = "Command-line interface for rustypdf."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme = "../README.md"
keywords = ["pdf", "markdown", "cli", "science"]
categories = ["command-line-utilities", "text-processing"]

[[bin]]
name = "rp2m"
path = "src/main.rs"

[dependencies]
rustypdf.workspace = true

anyhow.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
